version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    environment:
      - APP_ENV=local
      - APP_KEY=base64:w8AEiCJM9jsxgvimvpKvmXOHr/GbyOwlOUXVH1blDok=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=<your_db_name>
      - DB_USERNAME=<your_db_username>
      - DB_PASSWORD=<your_db_password>
      - NEWS_API_ORG_KEY=fbe4325628a741fdb716c380af4c8bab
      - GUARDIAN_API_KEY=9835f32b-bef0-41c5-8781-f5170c49a25a
      - NEW_YORK_TIMES_KEY=zUyNXLmthKpGTykYG9uydf7uKtn5eJQF
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=<your_db_name>
      - MYSQL_USER=<your_db_username>
      - MYSQL_PASSWORD=<your_db_password>
      - MYSQL_ROOT_PASSWORD=<your_db_root_password>
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
